// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGixjnzeLjcPMOPwsPP4u7_gdBPzUsWE8',
    appId: '1:198339879820:web:b8bbf8fed71fb417cc2ca9',
    messagingSenderId: '198339879820',
    projectId: 'mymoney-9052b',
    authDomain: 'mymoney-9052b.firebaseapp.com',
    storageBucket: 'mymoney-9052b.appspot.com',
    measurementId: 'G-BG8CTRN150',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvqGnfbdFh8e9GXY0tlZ1UU85V2AF3gMs',
    appId: '1:198339879820:android:0cce897ea8bee3e0cc2ca9',
    messagingSenderId: '198339879820',
    projectId: 'mymoney-9052b',
    storageBucket: 'mymoney-9052b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzu5zM7MIN4U2P-nwZX3HGh3bp_3rCsS8',
    appId: '1:198339879820:ios:0498ce45f0379e67cc2ca9',
    messagingSenderId: '198339879820',
    projectId: 'mymoney-9052b',
    storageBucket: 'mymoney-9052b.appspot.com',
    iosClientId: '198339879820-3n832cthk99ckh70rpdrua69e0ho83lj.apps.googleusercontent.com',
    iosBundleId: 'com.example.mymoney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzu5zM7MIN4U2P-nwZX3HGh3bp_3rCsS8',
    appId: '1:198339879820:ios:9a59791013427e1ecc2ca9',
    messagingSenderId: '198339879820',
    projectId: 'mymoney-9052b',
    storageBucket: 'mymoney-9052b.appspot.com',
    iosClientId: '198339879820-uir15ov4m14c3gvkdnh8ln6iid6jt54m.apps.googleusercontent.com',
    iosBundleId: 'com.example.mymoney.RunnerTests',
  );
}
